# OpenCV YOLO Pose Detection - RTSP Configuration File
# Special settings for RTSP camera - shares main database

# Camera Settings
camera:
  # RTSP URL format: "rtsp://username:password@ip:port/stream"
  source: "rtsp://username:password@ip:port/stream"  # Change this to your camera URL
  resolution: [1280, 720]       # Higher resolution for RTSP
  buffer_size: 10              # Large buffer - prevents frame loss, for smoothness
  
# YOLO Model Settings
yolo:
  model_path: "yolo11n-pose.pt"  # Model file path
  device: "auto"                 # "auto", "cpu", "cuda" - automatic GPU detection
  
# Tracking Settings
tracking:
  # TrackManager Parameters
  max_history_length: 30       # Track history length
  
  # Norfair Parameters
  use_norfair: true            # Use Norfair tracker
  distance_function: "keypoint"  # "keypoint" - OKS based distance
  distance_threshold: 0.3       # OCCLUSION OPTIMIZED: Matches even when overlapping (0.8 → 0.3)
  hit_counter_max: 300          # OCCLUSION OPTIMIZED: 10 seconds resilient (60 → 300)
  initialization_delay: 5       # ANTI-FLICKER: Wait 5 frames, filter temporary detections (2 → 5)
  pointwise_hit_counter_max: 8  # KALMAN FILTER: Remember keypoints longer (4 → 8)
  
  # ReID Parameters
  use_reid: true               # ReID active/inactive
  reid_distance_threshold: 0.4  # OCCLUSION OPTIMIZED: Easier recognition (0.5 → 0.4)
  reid_hit_counter_max: 450     # LONG OCCLUSION: 15 seconds active (150 → 450)
  keypoint_weight: 0.3          # WEIGHT BALANCED: Keypoint increased (0.1 → 0.3)
  reid_weight: 0.4              # WEIGHT BALANCED: ReID increased (0.2 → 0.4)
  skeletal_weight: 0.3          # WEIGHT BALANCED: Skeletal reduced, changes in occlusion (0.7 → 0.3)
  use_skeletal: true            # Skeletal biometrics active
  
  # Persistent Database - SAME DATABASE!
  use_persistent_reid: true     # Persistent database active
  persistent_db_path: "person_database.json"  # MAIN DATABASE - shared with webcam
  persistent_db_type: "json"    # "json" or "sqlite"
  persistent_similarity_threshold: 0.70  # OPTIMIZED: Recognizes same people, distinguishes different ones
  max_persons: 1000            # Maximum person count
  auto_save: true               # Auto save
  
# Performance Settings
performance:
  track_every_n_frames: 1       # Process every frame - maximum smoothness (delay not important)
  
# UI Settings
ui:
  window_name: "YOLO11 Pose Detection - RTSP"  # Special window name for RTSP
  
# Logging Settings
logging:
  log_to_file: true            # Write logs to file
  log_file: "logs/yolo_rtsp_detection.log"  # Special log file for RTSP

# Detection Settings
detection:
  conf_threshold: 0.25          # Confidence threshold for detection
  iou_threshold: 0.4            # IOU threshold for tracking
  keypoint_confidence: 0.3      # Minimum keypoint confidence
  min_visible_keypoints: 5      # SECURITY LAYER: For quality detection increased (5 → 8)
  show_keypoint_numbers: true   # Show keypoint numbers on skeleton
  
# Pose Measurement Settings
pose_measurement:
  default_body_height_cm: 170   # Default body height in cm
  average_shoulder_width_cm: 45 # Average shoulder width in cm
  min_face_width_pixels: 20     # Minimum face width for head pose
  yaw_scale_degrees: 30         # Yaw angle scale factor
  pitch_scale_degrees: 45       # Pitch angle scale factor
  
# Skeletal Biometrics Settings
skeletal:
  min_quality_measurements: 6   # FLEXIBLE: Skeletal optional, embedding sufficient (10 → 6)
  alpha_embedding: 0.9          # Exponential moving average for embeddings
  alpha_skeletal: 0.7           # Exponential moving average for skeletal features
  
# RTSP Settings
rtsp:
  max_consecutive_failures: 15  # Max failed frames before reconnect